document.addEventListener("DOMContentLoaded",()=>{const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
setTimeout(()=>document.body.classList.add("loaded"),2200);
const header=$(".header");const progress=$(".progress");
function scroll(){header.classList.toggle("scrolled",scrollY>35);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=max>0?(scrollY/max*100)+"%":"0%"}addEventListener("scroll",scroll,{passive:true});scroll();

const reveals=$$(".reveal");if("IntersectionObserver"in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -60px"});reveals.forEach((el,i)=>{el.style.transitionDelay=Math.min(i*35,280)+"ms";io.observe(el)})}else reveals.forEach(e=>e.classList.add("visible"));

if(!reduce){const targets=$$(".typing,.hero-copy");targets.forEach((el,index)=>{if(index>0||el.dataset.typed)return;const original=el.textContent.trim();if(!original)return;const lines=[original,"I turn ideas into websites, apps and Minecraft projects.","Always building. Always experimenting."];let line=0,pos=0,deleting=false;el.dataset.typed="true";el.classList.add("typing-active");function type(){const text=lines[line%lines.length];el.textContent=text.slice(0,pos);if(!deleting&&pos<text.length){pos++;setTimeout(type,28)}else if(!deleting){deleting=true;setTimeout(type,1700)}else if(pos>0){pos--;setTimeout(type,14)}else{deleting=false;line++;setTimeout(type,350)}}el.textContent="";type()})}

if(!reduce){$$('h2,.hero-title,.section-top,.hero-copy').forEach(el=>{el.classList.add("motion-target");if(!el.querySelector('.motion-streak')){const streak=document.createElement("span");streak.className="motion-streak";el.appendChild(streak)}});$$('a,.button,.project-card').forEach(el=>{el.addEventListener("mouseenter",()=>el.classList.add("motion-hover"));el.addEventListener("mouseleave",()=>el.classList.remove("motion-hover"))})}

if(!reduce&&!matchMedia("(pointer:coarse)").matches){const glow=$(".cursor-glow"),ring=$(".cursor-ring"),dot=$(".cursor-dot");let tx=-100,ty=-100,rx=-100,ry=-100,gx=-100,gy=-100;addEventListener("mousemove",e=>{tx=e.clientX;ty=e.clientY});function cursor(){rx+=(tx-rx)*.18;ry+=(ty-ry)*.18;gx+=(tx-gx)*.08;gy+=(ty-gy)*.08;ring.style.left=rx+"px";ring.style.top=ry+"px";dot.style.left=tx+"px";dot.style.top=ty+"px";glow.style.left=gx+"px";glow.style.top=gy+"px";requestAnimationFrame(cursor)}cursor();$$('a,.magnetic-card').forEach(el=>{el.addEventListener("mouseenter",()=>ring.classList.add("active"));el.addEventListener("mouseleave",()=>ring.classList.remove("active"))});$$('.magnetic').forEach(el=>el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform='translate('+(e.clientX-r.left-r.width/2)*.12+'px,'+(e.clientY-r.top-r.height/2)*.12+'px)'}));$$('.magnetic').forEach(el=>el.addEventListener('mouseleave',()=>el.style.transform=''));$$('.magnetic-card').forEach(card=>card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;card.style.transform='perspective(1000px) rotateX('+(-y/r.height*5)+'deg) rotateY('+(x/r.width*5)+'deg) translateY(-6px)';card.style.setProperty('--mx',e.clientX-r.left+'px');card.style.setProperty('--my',e.clientY-r.top+'px')}));$$('.magnetic-card').forEach(card=>card.addEventListener('mouseleave',()=>card.style.transform=''))}

$$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=$(a.getAttribute("href"));if(t){e.preventDefault();t.scrollIntoView({behavior:reduce?"auto":"smooth"})}}));
const sections=[...$$('main section[id]')];const dockItems=[...$$('.dock-item')];if('IntersectionObserver'in window){const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){dockItems.forEach(item=>item.classList.toggle('active',item.getAttribute('href')==='#'+entry.target.id))}})},{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(section=>sectionObserver.observe(section))}
const ticker=$(".ticker");if(ticker&&!reduce){const items=ticker.innerHTML;ticker.innerHTML=items+items;let x=0;function tick(){x-=.35;if(Math.abs(x)>ticker.scrollWidth/2)x=0;ticker.style.transform="translateX("+x+"px");requestAnimationFrame(tick)}tick()}
});